services:
  snowsignal:
    image: harbor.stfc.ac.uk/isis-accelerator-controls/snowsignal:main
    environment:
      SERVICENAME: '{{.Service.Name}}'
    networks:
      - snowsignal-test
    deploy: 
      mode: global
      placement:
         max_replicas_per_node: 1

networks:
  snowsignal-test:
    external: true
