# Use slim because if we used alpine we'd need gcc for the 
# psutils requirement in requirements.txt
FROM python:3.12-slim

ADD requirements.txt /snowsignal/
WORKDIR /snowsignal
RUN pip install -r requirements.txt
ADD *.py /snowsignal/src/

CMD ["python", "-m", "snowsignal.snowsignal"]