# Use slim because if we used alpine we'd need gcc for the 
# psutils requirement in requirements.txt
FROM python:3.12-slim

# Token has read_api and read_repository permissions and so does not need to be kept secret
# However it will expire
RUN pip install SnowSignal --index-url https://gitlab.stfc.ac.uk/api/v4/projects/5671/packages/pypi/simple 

CMD ["python", "-m", "snowsignal"]
