# Use slim because if we used alpine we'd need gcc for the 
# psutils requirement in requirements.txt
FROM python:3.12-slim

#RUN apt update && apt install -y libpcap0.8
ADD requirements.txt /snowsignal/
WORKDIR /snowsignal
RUN pip install -r requirements.txt
ADD *.py /snowsignal/

CMD ["python", "-m src.snowsignal"]